title: COZ GIS Wiki

description: A website documenting GIS and data workflows for the City of Zanesville.
baseurl: ""
url: "https://zanesville.github.io/"

# permalink: :categories/:title/
highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "posts"
      permalink: /docs/:title/
  -
    scope:
      path: "_tags"
    values:
      layout: "tags"

plugins:
  - jekyll-admin

sass:
  sass_dir: _sass

include: 
  - _tags

exclude: ["package.json", "package-lock.json", "README.md"]