title: COZ GIS Wiki

description: A website documenting GIS and data workflows for the City of Zanesville.
baseurl: "https://zanesville.github.io/wiki"
url: "https://zanesville.github.io/"

# permalink: :categories/:title/
highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "posts"
      permalink: /:categories/:title/
      category: docs

plugins: 
  - jekyll-admin
  - jekyll/tagging

sass:
  sass_dir: _sass

exclude: ["package.json", "package-lock.json", "README.md"]

tag_page_layout: tags
tag_page_dir: tags
tag_permalink_style: pretty
