title: COZ GIS Wiki

description: A website documenting GIS and data workflows for the City of Zanesville.
baseurl: "/wiki"

# permalink: :categories/:title/
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      permalink: /:categories/:title/

plugins: 
  - jekyll-admin
#  - jekyll/tagging
  - jekyll-archives

jekyll-archives:
  enabled: ["categories", "tags"]
  layout: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/docs/:name/'

sass:
  sass_dir: _sass

exclude: ["package.json", "package-lock.json", "README.md"]

tag_page_layout: tags
tag_page_dir: tags
tag_permalink_style: pretty

category_icons:
  apps: layers.svg
  data: layers.svg
  research: layers.svg
  tasks: layers.svg
  tips: layers.svg
  x-archive: layers.svg