title: Zanesville GIS
description: A website documenting GIS and data workflows for the City of Zanesville.
baseurl: "/wiki"

# permalink: :categories/:title/
highlighter: rouge

permalink: /:title/

defaults:
  -
    scope:
      path: "_categories"
      type: "pages"
    values:
      layout: "category"
      permalink: /:title/
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      permalink: /:categories/:title/
      category: "documents" #default category
      tags: ["gis"]

plugins: 
  - jekyll-admin

sass:
  sass_dir: _sass

include: 
 - _pages
 - _categories

exclude: ["package.json", "package-lock.json"]

#tag_page_layout: tags
#tag_page_dir: tags
#tag_permalink_style: pretty