title: COZ GIS Wiki

description: A website documenting GIS and data workflows for the City of Zanesville.
baseurl: "/wiki"

# permalink: :categories/:title/
highlighter: rouge

permalink: /:title/

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      permalink: /:categories/:title/

# plugins: 
  # - jekyll-admin

# jekyll-archives:
#   enabled: ["categories", "tags"]
#   layout: category
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/docs/:name/'

sass:
  sass_dir: _sass

include: 
 - _pages

exclude: ["package.json", "package-lock.json", "README.md"]

#tag_page_layout: tags
#tag_page_dir: tags
#tag_permalink_style: pretty